version: '3.8'

networks:
  app-network:

services:
  node_redis:
    container_name: node_redis
    image: redis:7.0-alpine
    networks:
      - app-network
    ports:
      - 6379:6379
    volumes:
      - redis_volume:/var/lib/redis/data

  node_backend:
    build: .
    networks:
      - app-network
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - PORT=4000
      - REDIS_HOST=node_redis
      - RSS_URL=https://www.rotanacareers.com/rss/all-rss.xml/
    depends_on:
      - node_redis

volumes:
  redis_volume: {}
